let val;
val = document;
val = document.all;
val = document.all.length;
val = document.head;
val = document.body;
val = document.body.doctype;
val= document.domain;
val = document.contentType;
val = document.URL;
val= document.characterSet;

val= document.forms;
val = document.forms[0];
val = document.forms[0].id;
val = document.forms[0].classList;
val = document.forms[0].attributes;
val = document.forms[0].action;
val = document.forms[0].method;
val = document.all;
let tagsArr = Array.from(val);
val = document.scripts;
console.log(val);