console.log('Hello World')
console.log(123)
console.log(true)
console.log([1,2,3,4,5])
console.warn('This is Warning')
console.table({1:"a",2:"b",3:"c",4:"d"})
console.log(true)
console.clear()
console.error('This is error')